# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-28 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booxtream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boox',
            name='download_link_mobi',
        ),
    ]
