# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180720_1413'),
    ]

    operations = [
        migrations.RunSQL(
            ['CREATE FULLTEXT INDEX core_work_index ON core_work (title);'],
            ['DROP INDEX core_work_index on core_work;'],
        ),    
        migrations.RunSQL(
            ['CREATE FULLTEXT INDEX core_author_index ON core_author (name);'],
            ['DROP INDEX core_author_index on core_author;'], 
        ),    
    ]
