# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181108_1646'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=[b'work'], name='core_editio_work_id_3ae536_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=[b'name'], name='core_author_name_fca240_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=[b'name'], name='core_subjec_name_36111e_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=[b'is_free', b'title'], name='core_work_is_free_1e4d06_idx'),
        ),
    ]
