# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190227_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acq',
            name='license',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual license'), (2, 'Library License'), (3, 'Borrowed from Library'), (0, 'Just for Testing'), (4, 'On Reserve'), (5, 'Already Thanked')], default=1),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='license',
            field=models.CharField(choices=[('CC BY-NC-ND', 'Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported (CC BY-NC-ND 3.0)'), ('CC BY-NC-SA', 'Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)'), ('CC BY-NC', 'Creative Commons Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)'), ('CC BY-ND', 'Creative Commons Attribution-NoDerivs 3.0 Unported (CC BY-ND 3.0)'), ('CC BY-SA', 'Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)'), ('CC BY', 'Creative Commons Attribution 3.0 Unported (CC BY 3.0)'), ('CC0', 'No Rights Reserved (CC0)'), ('GFDL', 'GNU Free Documentation License'), ('LAL', 'Licence Art Libre'), ('OSI', 'OSI Approved License')], default='CC BY-NC-ND', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('INITIALIZED', 'INITIALIZED'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('WITHDRAWN', 'WITHDRAWN'), ('SUCCESSFUL', 'SUCCESSFUL'), ('UNSUCCESSFUL', 'UNSUCCESSFUL')], db_index=True, default='INITIALIZED', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pledge-to-unglue campaign'), (2, 'Buy-to-unglue campaign'), (3, 'Thanks-for-ungluing campaign')], default=1),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('active', 'Claim has been accepted.'), ('pending', 'Claim is pending acceptance.'), ('release', 'Claim has not been accepted.')], default='active', max_length=7),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('html', 'HTML'), ('text', 'TEXT'), ('mobi', 'MOBI')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='rights',
            field=models.CharField(choices=[('CC BY-NC-ND', 'Creative Commons Attribution-NonCommercial-NoDerivs'), ('CC BY-NC-SA', 'Creative Commons Attribution-NonCommercial-ShareAlike'), ('CC BY-NC', 'Creative Commons Attribution-NonCommercial'), ('CC BY-ND', 'Creative Commons Attribution-NoDerivs'), ('CC BY-SA', 'Creative Commons Attribution-ShareAlike'), ('CC BY', 'Creative Commons Attribution'), ('CC0', 'No Rights Reserved (CC0)'), ('GFDL', 'GNU Free Documentation License'), ('LAL', 'Licence Art Libre'), ('OSI', 'OSI Approved License'), ('PD-US', 'Public Domain, US')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='version_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ebookfile',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('html', 'HTML'), ('text', 'TEXT'), ('mobi', 'MOBI')], max_length=25),
        ),
        migrations.AlterField(
            model_name='gift',
            name='message',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='libpref',
            name='marc_link_target',
            field=models.CharField(choices=[('DIRECT', 'Raw link'), ('UNGLUE', 'Unglue.it link')], default='UNGLUE', max_length=6, verbose_name='MARC record link targets'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='license',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual license'), (2, 'Library License')], default=1),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='rightsholder',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='rightsholder',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rightsholder',
            name='mailing',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='rightsholder',
            name='signature',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rightsholder',
            name='signer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rightsholder',
            name='signer_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='authority',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_source',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Avatar, Please'), (1, 'Gravatar'), (2, 'Twitter/Facebook'), (4, 'Unglueitar')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='age_level',
            field=models.CharField(blank=True, choices=[('', 'No Rating'), ('5-6', "Children's - Kindergarten, Age 5-6"), ('6-7', "Children's - Grade 1-2, Age 6-7"), ('7-8', "Children's - Grade 2-3, Age 7-8"), ('8-9', "Children's - Grade 3-4, Age 8-9"), ('9-11', "Children's - Grade 4-6, Age 9-11"), ('12-14', 'Teen - Grade 7-9, Age 12-14'), ('15-18', 'Teen - Grade 10-12, Age 15-18'), ('18-', 'Adult/Advanced Reader')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='workrelation',
            name='relation',
            field=models.CharField(choices=[('translation', 'translation'), ('revision', 'revision'), ('sequel', 'sequel'), ('part', 'part')], max_length=15),
        ),
    ]
