# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-17 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200214_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key',
        ),
    ]
