# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_source',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Avatar, Please'), (1, 'Gravatar'), (2, 'Twitter'), (4, 'Unglueitar')], default=4, null=True),
        ),
    ]
