# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200720_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrelation',
            name='relation',
            field=models.CharField(choices=[('translation', 'translation'), ('revision', 'revision'), ('sequel', 'sequel'), ('part', 'part'), ('unspecified', 'unspecified')], max_length=15),
        ),
    ]
