# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200806_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('html', 'HTML'), ('text', 'TEXT'), ('mobi', 'MOBI'), ('online', 'Online Only')], max_length=25),
        ),
    ]
