# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200812_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='goodreads_auth_secret',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goodreads_auth_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goodreads_user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goodreads_user_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goodreads_user_name',
        ),
    ]
