# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201210_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookfile',
            name='source',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
