# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-28 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210503_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookfile',
            name='mobied',
        ),
    ]
