# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20230105_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='num_free',
            field=models.IntegerField(default=0),
        ),
    ]
