# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-19 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    def count_free(apps, schema_editor):
        """
        Now that subject has num_free filed, populate it 
        """
        Subject = apps.get_model('core', 'Subject')
        for subject in Subject.objects.all():
            subject.num_free = subject.works.filter(is_free=True).count()
            subject.save()
            
    def noop(apps, schema_editor):
        pass

    dependencies = [
        ('core', '0027_subject_num_free'),
    ]

    operations = [
        migrations.RunPython(count_free, reverse_code=noop, hints={'core': 'Subject'}),
    ]
