# Generated by Django 5.2.15 on 2026-09-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_drop_comment_tables'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_free', 'language', '-featured', '-created'], name='core_work_free_lang_new_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_free', '-featured', '-created'], name='core_work_free_new_idx'),
        ),
    ]
