# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='host',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('EXPIRED', 'EXPIRED'), ('EXPIRING', 'EXPIRING'), ('ERROR', 'ERROR')], default='ACTIVE', max_length=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='host',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='local_status',
            field=models.CharField(default='NONE', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
