# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryauth', '0003_badusernamepattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='backend',
            field=models.CharField(choices=[('ip', 'IP authentication'), ('cardnum', 'Library Card Number check'), ('email', 'e-mail pattern check')], default='ip', max_length=10),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
