# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='protocol',
            field=models.CharField(default='ftp', max_length=10),
        ),
    ]
