#!/bin/bash

# put this in one of root's crontabs and it'll refresh and restart regluit

cd /opt/regluit
sudo -u ubuntu -c "git pull"
source ENV/bin/activate
django-admin.py syncdb --migrate --settings regluit.settings.prod
sudo /etc/init.d/apache2 restart
sudo /etc/init.d/celeryd restart
touch /opt/regluit/deploy/last-update
