# Generated by Django 4.2.21 on 2026-04-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bisacheading',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bisacheading',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bisacheading',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
